spring.application.name=ecsample
#db設定
spring.datasource.url=jdbc:postgresql://localhost:5432/ecsample_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# SQL初期化の設定 (schema.sql, data.sqlを起動時に実行する)
spring.sql.init.mode=always

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true